LEG1:
  kinematics_solver: daedalus_LEG1_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 5
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LEG2:
  kinematics_solver: daedalus_LEG2_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LEG3:
  kinematics_solver: daedalus_LEG3_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LEG4:
  kinematics_solver: daedalus_LEG4_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
