controller_list:
  - name: LEG1_controller
    joints:
      - leg1joint1
      - leg1joint2
      - leg1joint3
      - leg1joint4
      - leg1joint5
  - name: LEG2_controller
    joints:
      - leg2joint1
      - leg2joint2
      - leg2joint3
      - leg2joint4
      - leg2joint5
  - name: LEG3_controller
    joints:
      - leg3joint1
      - leg3joint2
      - leg3joint3
      - leg3joint4
      - leg3joint5
  - name: LEG4_controller
    joints:
      - leg4joint1
      - leg4joint2
      - leg4joint3
      - leg4joint4
      - leg4joint5
  - name: FOOT1_controller
    joints:
      - leg1joint4
      - leg1joint5
  - name: FOOT2_controller
    joints:
      - leg2joint4
      - leg2joint5
  - name: FOOT3_controller
    joints:
      - leg3joint4
      - leg3joint5
  - name: FOOT4_controller
    joints:
      - leg4joint4
      - leg4joint5
