controller_list:
  - name: fake_LEG1_controller
    joints:
      - leg1joint1
      - leg1joint2
      - leg1joint3
      - leg1joint4
      - leg1joint5
  - name: fake_LEG2_controller
    joints:
      - leg2joint1
      - leg2joint2
      - leg2joint3
      - leg2joint4
      - leg2joint5
  - name: fake_LEG3_controller
    joints:
      - leg3joint1
      - leg3joint2
      - leg3joint3
      - leg3joint4
      - leg3joint5
  - name: fake_LEG4_controller
    joints:
      - leg4joint1
      - leg4joint2
      - leg4joint3
      - leg4joint4
      - leg4joint5
  - name: fake_FOOT1_controller
    joints:
      - leg1joint4
      - leg1joint5
  - name: fake_FOOT2_controller
    joints:
      - leg2joint4
      - leg2joint5
  - name: fake_FOOT3_controller
    joints:
      - leg3joint4
      - leg3joint5
  - name: fake_FOOT4_controller
    joints:
      - leg4joint4
      - leg4joint5