daedalus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1joint1
    pid: {p: 1000.0, i: 0.01, d: 1000.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1joint2
    pid: {p: 1000.0, i: 0.01, d: 1000.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1joint3
    pid: {p: 1000.0, i: 0.01, d: 1000.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1joint4
    pid: {p: 1000.0, i: 0.01, d: 1000.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1joint5
    pid: {p: 1000.0, i: 0.01, d: 1000.0}
